<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices, print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [7]:
# here A and B are list of lists
def matrix_mul(x, y):
    #print(len(x[0]), len(y))
    if len(x[0]) == len(y): 
        re = []
        for z in range(len(x)):
            re.append([0 for y in range(len(y[1]))])
        
        for i in range(len(x)):
            for j in range(len(y[0])):
                for k in range(len(y)):
                    re[i][j] += x[i][k] * y[k][j]
        return re
    else:
        return "Not Possible"
    
#x   = [[1, 2], [3, 4]]
x   = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]
y   = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
#y   = [[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]
#y = [[1,4], [5,6], [7,8], [9,6]]
    
matrix_mul(x, y)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

In [4]:
import numpy as np

np.matmul(x, y)


array([[1, 3, 4],
       [2, 5, 7],
       [5, 9, 6]])

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [8]:
from random import uniform

def pick_a_number_from_list(A):
    sum_a = sum(A)
    normalized_, cum_nor_sum, r = [], [], 0
    for x in A:
        di = x / sum_a
        normalized_.append(di)
    #print(normalized_, sum(normalized_))
    
    for x in range(len(normalized_)):
        if len(cum_nor_sum) == 0:
            cum_nor_sum.append(normalized_[x])
        else:
            z = normalized_[x] + cum_nor_sum[x-1]
            cum_nor_sum.append(z)
    #print(cum_nor_sum, sum(cum_nor_sum))    
    
    r = uniform(0.0, 1.0)
    
    for x in range(len(cum_nor_sum)):
        if r <= cum_nor_sum[x]:
            return A[x]
        

def sampling_based_on_magnitued():
    A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

100
79
28
100
100
100
79
27
79
100
27
79
100
79
27
45
13
100
79
79
10
45
100
10
6
13
100
27
10
79
79
100
27
28
100
27
45
27
100
100
45
45
45
45
100
10
100
45
100
100
13
79
100
27
79
79
27
100
10
100
100
100
100
27
79
100
100
79
100
45
6
79
45
100
79
27
27
27
100
79
28
79
79
100
100
28
28
45
79
28
45
28
45
10
100
79
28
13
45


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [12]:
#import re

# String: it will be the input to your program
def replace_digits(String):
    r = ""
    for x in String:
        try:
            int(x)
        except(Exception) as e:
            #r += "-" # if you want to add special char for non-int chars
            pass
        else:
            r += "#"
        
    return(r) 

String = "234jay"
replace_digits(String)

'###'

<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [13]:

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def display_dash_board(students, marks):
    
    # code for computing top 5 students
    dec_marks = sorted(marks, reverse=True)
    top_5, least_5, students_25_75 = {}, {}, {}
    #print(dec_marks)
    for x in range(0, 5):
        top_5[students[marks.index(dec_marks[x])]] = marks[x]
    top_5_students = top_5
    
    # code for computing top least 5 students
    asc_marks = sorted(marks)
    #print(asc_marks)
    for x in range(0, 5):
        least_5[students[marks.index(asc_marks[x])]] = marks[x]
    least_5_students = least_5
    
    # code for computing students_within_25_and_75
    n = len(marks)
    first_quartile = int(n/4) if (n/4) else int(n/4) + 1
    third_quartile = int(3*n/4)
    #print(first_quartile, third_quartile)
    for x in range(first_quartile, third_quartile):
        students_25_75[students[marks.index(asc_marks[x])]] = asc_marks[x]
    students_within_25_and_75 = students_25_75
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(top_5_students, "\n", least_5_students, "\n", students_within_25_and_75)

{'student8': 45, 'student10': 78, 'student2': 12, 'student5': 14, 'student7': 48} 
 {'student3': 45, 'student4': 78, 'student9': 12, 'student6': 14, 'student1': 48} 
 {'student9': 35, 'student6': 43, 'student1': 45, 'student7': 47, 'student5': 48}


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [14]:
import math


# here S is list of tuples and P is a tuple of len=2
def closest_points_to_p(S, P):
    dis_, closest_points_to_p = {}, []
    
    for z in S:
        a = (z[0] * P[0]) + (z[1] * P[1])
        a1_ = math.sqrt((z[0]**2) + (z[1]**2))
        a2_ = math.sqrt((P[0]**2) + (P[1]**2))
        d = 1 - (a / (a1_ * a2_))
        #print(z, d)
        dis_[z] = d
    
    sorted_dis = sorted(dis_.items(), key=lambda x: x[1])
    #print(sorted_dis)
    
    for x in sorted_dis[:5]:
        closest_points_to_p.append(x[0])
    return closest_points_to_p  # its list of tuples

S = [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P = (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [15]:
import math
import re

def i_am_the_one(red, blue, line):
    z = re.findall(r'[\d\.\-\+]+', i)
    #print(z)
    reds, blues = [], []
    for r,b in zip(red, blue):
        red_, blue_ = None, None
        red_ = (float(z[0]) * r[0]) + (float(z[1]) * r[1]) + float(z[2])
        blue_ = (float(z[0]) * b[0]) + (float(z[1]) * b[1]) + float(z[2])
        #print(red_, blue_) 
        
        reds.append(0) if red_ < 0 else reds.append(1)
        blues.append(0) if blue_ < 0 else blues.append(1)
    
    if all(reds) and not all(blues) or all(blues) and not all(reds):
        return "Yes"
    else:
        return "No"
    

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [16]:
def first_last_in(s, l):
    z = []
    ele = int(s) // l
    for i in range(l):
        z.append(ele)
    return z
    
def middle_wicket(s, x):
    z = []
    if s[0] != "_" and s[-1] != "_":
        sum_ = int(s[0]) + int(s[-1])
        z = first_last_in(sum_, len(s))
    elif 0 not in x:
        for i in x:
            w = None
            if x.index(i) == 0:
                i += 1
                w = int(s[i-1]) // i
                for j in range(0, i):
                    z.append(w)
            else:
                i += 1
                w = ( z[-1] + int(s[i-1]) ) // (i - x[x.index(i-1)-1]) 
                for j in range(x[x.index(i-1)-1], i):
                    if len(z) - j == 1:
                        z[j] = w
                    else:
                        z.append(w)
        else:
            w = z[-1] // ((len(s)+1) - len(z))
            for i in range(len(z), len(s)+1):
                z.append(w)
    return z

def curve_smoothing(string):
    s = string.split(",")
    x = [s.index(x) for x in s if x != "_"]
    
    if len(x) == 1:
        return first_last_in(s[x[0]], len(s))
    elif len(x) > 1:
        return middle_wicket(s, x)

#S = "_,_,30,_,_,10,_,50,_"
#S = "80,_,_,_,_"
#S = "_,_,_,24"
S = "40,_,_,_,60"

smoothed_values = curve_smoothing(S)
print(smoothed_values)

[20, 20, 20, 20, 20]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
Find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [17]:
def compute_conditional_probabilites(A):
    for i in range(1, 4):
        for j in range(1, 6):
            intersection = [1 for x in A if 'S'+str(i) in x and 'F'+str(j) in x]
            gvn = [1 for x in A if 'S'+str(i) in x]
            print('F'+str(j), 'S'+str(i), "{0:.2f}".format(sum(intersection)/ sum(gvn)))
        print("\n")
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

F1 S1 0.25
F2 S1 0.25
F3 S1 0.00
F4 S1 0.25
F5 S1 0.25


F1 S2 0.33
F2 S2 0.33
F3 S2 0.33
F4 S2 0.00
F5 S2 0.00


F1 S3 0.00
F2 S3 0.33
F3 S3 0.33
F4 S3 0.33
F5 S3 0.00




<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [18]:

def string_features(S1, S2):
    a,b,c = 0, [], []
    a = sum([1 for x in S1.split() if x in S2])
    b = [x for x in S1.split() if x not in S2]
    c = [x for x in S2.split() if x not in S1]
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

7 ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>

Find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.42431
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [19]:

import math

def compute_log_loss(A):
    l = 0
    for i in A:
        #print(  (i[0] * math.log10(i[1])) + ((1-i[0]) * math.log10((1-i[1])))  )
        l += (i[0] * math.log10(i[1])) + ((1-i[0]) * math.log10((1-i[1])))
    
    return (-1 / len(A)) * l

#A = [[1, 0.1], [0, 0.9], [0, 0.9], [0, 0.8], [0, 0.9], [1, 0.1], [1, 0.1], [1, 0.2]]
#A = [[1, 0.9], [0, 0.1], [0, 0.02], [0, 0.01], [0, 0.004], [1, 0.99], [1, 0.94], [1, 0.84]]
A = [[0, 0.8], [0, 0.9], [0, 0.7], [0, 0.85], [0, 0.91], [0, 0.81], [0, 0.71], [0, 0.82]]
loss = compute_log_loss(A)
print(loss)

0.7618863596457822
